name: CI
on:
  push:
    branches: [ main ]
    paths: [ 'pom.xml', 'src/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'pom.xml', 'src/**' ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test (${{ matrix.os }}, JDK ${{ matrix.java }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
        exclude:
          - os: windows-latest
            java: 21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build & Unit tests
        run: mvn -B -DskipTests=false test

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-${{ matrix.os }}-jdk${{ matrix.java }}
          path: target/surefire-reports

      - name: Upload JaCoCo XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-${{ matrix.os }}-jdk${{ matrix.java }}
          path: target/site/jacoco/jacoco.xml
